# Generated by Django 4.2.7 on 2025-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='chunk_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
